/**
 * API endpoint para servir el script de instalación de Windows TPV
 * 
 * Genera un script de PowerShell que:
 * - Muestra mensajes claros de lo que está haciendo
 * - Mantiene la ventana abierta si hay errores
 * - Proporciona instrucciones de uso
 * - Es compatible con PowerShell 5.1+
 */

import { NextApiRequest, NextApiResponse } from "next";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  // Solo permitir método GET
  if (req.method !== "GET") {
    return res.status(405).json({ error: "Metodo no permitido" });
  }

  // Verificar que el usuario esta autenticado y tiene rol de cajero
  try {
    const profileResp = await fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000"}/api/user/profile`, {
      headers: {
        Cookie: req.headers.cookie || "",
      },
    });

    if (!profileResp.ok) {
      return res.status(401).json({ error: "No autenticado" });
    }

    const profile = await profileResp.json();
    if (profile.user?.role !== "cajero") {
      return res.status(403).json({ error: "Acceso solo para cajeros" });
    }
  } catch {
    return res.status(401).json({ error: "No autenticado" });
  }

  // Generar el script de instalacion de PowerShell
  const installScript = generateInstallScript();

  // Configurar headers para descarga
  res.setHeader("Content-Type", "text/plain; charset=utf-8");
  res.setHeader("Content-Disposition", "attachment; filename=install-tpv-windows.ps1");

  return res.status(200).send(installScript);
}

function generateInstallScript(): string {
  const PROTOCOL_NAME = "clubviveverde";
  const PROTOCOL_URL = PROTOCOL_NAME + "://";
  
  const lines: string[] = [
    "# Club ViveVerde TPV - Instalador Automatico para Windows",
    "# IMPORTANTE: Ejecutar como Administrador",
    "# Version: 2.2.0",
    "",
    "$ErrorActionPreference = \"Continue\"",
    "$scriptErrorOccurred = $false",
    "$scriptErrorMessage = \"\"",
    "",
    "# Configuracion",
    "$APP_NAME = \"Club ViveVerde TPV\"",
    "$REPO_URL = \"https://github.com/idalonso123/CLUB.git\"",
    "$PROTOCOL = \"" + PROTOCOL_NAME + "\"",
    "$PROTOCOL_URL = \"" + PROTOCOL_URL + "\"",
    "$INSTALL_DIR = Join-Path $env:USERPROFILE \".clubviveverde-tpv\"",
    "",
    "function Write-Header {",
    "    param([string]$Message)",
    "    Write-Host \"\"",
    "    Write-Host \"========================================\" -ForegroundColor Cyan",
    "    Write-Host \" $Message\" -ForegroundColor Cyan",
    "    Write-Host \"========================================\" -ForegroundColor Cyan",
    "}",
    "",
    "function Write-Step {",
    "    param([int]$Num, [int]$Total, [string]$Message)",
    "    Write-Host \"\"",
    "    Write-Host \"[$Num/$Total] $Message\" -ForegroundColor Yellow",
    "}",
    "",
    "function Write-Success {",
    "    param([string]$Message)",
    "    Write-Host \"   [OK] $Message\" -ForegroundColor Green",
    "}",
    "",
    "function Write-Error-Msg {",
    "    param([string]$Message)",
    "    Write-Host \"   [ERROR] $Message\" -ForegroundColor Red",
    "}",
    "",
    "function Write-Warning-Msg {",
    "    param([string]$Message)",
    "    Write-Host \"   [ADVERTENCIA] $Message\" -ForegroundColor Yellow",
    "}",
    "",
    "function Record-Error {",
    "    param([string]$Message)",
    "    $script:scriptErrorOccurred = $true",
    "    $script:scriptErrorMessage += \"$Message`n\"",
    "    Write-Error-Msg $Message",
    "}",
    "",
    "function Test-Prerequisites {",
    "    Write-Step -Num 1 -Total 6 -Message \"Verificando prerrequisitos...\"",
    "    Write-Host \"   Esto verificara que tienes Node.js y Git instalados.\"",
    "    Write-Host \"\"",
    "",
    "    $nodePath = Get-Command node -ErrorAction SilentlyContinue",
    "    $gitPath = Get-Command git -ErrorAction SilentlyContinue",
    "    $npmPath = Get-Command npm -ErrorAction SilentlyContinue",
    "",
    "    if (-not $nodePath) {",
    "        Record-Error \"Node.js no encontrado\"",
    "        Write-Host \"   Solucion: Descarga e instala Node.js desde https://nodejs.org\" -ForegroundColor Yellow",
    "        return $false",
    "    }",
    "    Write-Success \"Node.js encontrado: $($nodePath.Source)\"",
    "    Write-Host \"   Version: $(node --version)\" -ForegroundColor Gray",
    "",
    "    if (-not $npmPath) {",
    "        Record-Error \"npm no encontrado (incluido con Node.js)\"",
    "        Write-Host \"   Solucion: Reinstalar Node.js desde https://nodejs.org\" -ForegroundColor Yellow",
    "        return $false",
    "    }",
    "    Write-Success \"npm encontrado: $(npm --version)\"",
    "",
    "    if (-not $gitPath) {",
    "        Record-Error \"Git no encontrado\"",
    "        Write-Host \"   Solucion: Descarga e instala Git desde https://git-scm.com\" -ForegroundColor Yellow",
    "        return $false",
    "    }",
    "    Write-Success \"Git encontrado: $($gitPath.Source)\"",
    "",
    "    return -not $scriptErrorOccurred",
    "}",
    "",
    "function Install-Application {",
    "    Write-Step -Num 2 -Total 6 -Message \"Preparando directorio de instalacion...\"",
    "    Write-Host \"   Directorio de instalacion: $INSTALL_DIR\"",
    "    Write-Host \"\"",
    "",
    "    if (Test-Path $INSTALL_DIR) {",
    "        Write-Warning-Msg \"El directorio de instalacion ya existe\"",
    "        $response = Read-Host \"   Deseas actualizar la aplicacion? (S/N)\"",
    "        if ($response -ne \"S\") {",
    "            Write-Host \"   Instalacion cancelada por el usuario.\" -ForegroundColor Yellow",
    "            return $false",
    "        }",
    "        Set-Location $INSTALL_DIR",
    "        Write-Host \"   Actualizando desde Git...\" -ForegroundColor Yellow",
    "        git pull origin main 2>&1 | Out-Null",
    "        if ($LASTEXITCODE -ne 0) {",
    "            Write-Warning-Msg \"No se pudo actualizar desde main, intentando master...\"",
    "            git pull origin master 2>&1 | Out-Null",
    "        }",
    "    } else {",
    "        Write-Host \"   Creando directorio...\" -ForegroundColor Yellow",
    "        try {",
    "            New-Item -ItemType Directory -Path $INSTALL_DIR -Force | Out-Null",
    "            Set-Location $INSTALL_DIR",
    "        } catch {",
    "            Record-Error \"No se pudo crear el directorio: $($_.Exception.Message)\"",
    "            return $false",
    "        }",
    "",
    "        Write-Step -Num 3 -Total 6 -Message \"Clonando repositorio...\"",
    "        Write-Host \"   Esto puede tardar varios minutos...\" -ForegroundColor Gray",
    "        Write-Host \"   URL: $REPO_URL\" -ForegroundColor Gray",
    "        Write-Host \"\"",
    "",
    "        try {",
    "            git clone $REPO_URL . 2>&1 | Out-Null",
    "            if ($LASTEXITCODE -ne 0) {",
    "                Write-Warning-Msg \"El clon inicial tuvo problemas, intentando de nuevo...\"",
    "                git clone $REPO_URL .",
    "            }",
    "        } catch {",
    "            Record-Error \"Error al clonar el repositorio: $($_.Exception.Message)\"",
    "            Write-Host \"   Solucion: Verifica tu conexion a internet.\" -ForegroundColor Yellow",
    "            return $false",
    "        }",
    "",
    "        if (-not (Test-Path \"package.json\")) {",
    "            Record-Error \"No se encontro el archivo package.json despues del clon\"",
    "            Write-Host \"   El repositorio puede estar vacio o no contiene los archivos correctos.\" -ForegroundColor Yellow",
    "            return $false",
    "        }",
    "    }",
    "",
    "    Write-Success \"Proyecto preparado exitosamente\"",
    "    return $true",
    "}",
    "",
    "function Install-Dependencies {",
    "    Write-Step -Num 4 -Total 6 -Message \"Instalando dependencias...\"",
    "    Write-Host \"   Ejecutando npm install...\"",
    "    Write-Host \"   Esto puede tardar varios minutos.\" -ForegroundColor Gray",
    "    Write-Host \"\"",
    "",
    "    try {",
    "        $npmOutput = npm install 2>&1",
    "        ",
    "        if ($LASTEXITCODE -eq 0) {",
    "            Write-Success \"Dependencias instaladas correctamente\"",
    "            return $true",
    "        } else {",
    "            Write-Warning-Msg \"npm install finalizo con codigo: $LASTEXITCODE\"",
    "            Write-Host \"   Intentando de nuevo...\" -ForegroundColor Yellow",
    "            npm install 2>&1 | Out-Null",
    "            if ($LASTEXITCODE -eq 0) {",
    "                Write-Success \"Dependencias instaladas en el segundo intento\"",
    "                return $true",
    "            } else {",
    "                Record-Error \"npm install no se ejecuto correctamente\"",
    "                Write-Host \"   Mensaje de npm:\" -ForegroundColor Yellow",
    "                $npmOutput | Select-Object -First 10 | ForEach-Object { Write-Host \"      $_\" -ForegroundColor Gray }",
    "                return $false",
    "            }",
    "        }",
    "    } catch {",
    "        Record-Error \"Error al ejecutar npm install: $($_.Exception.Message)\"",
    "        Write-Host \"   Solucion: Verifica que Node.js esta correctamente instalado.\" -ForegroundColor Yellow",
    "        return $false",
    "    }",
    "}",
    "",
    "function Register-Protocol {",
    "    Write-Step -Num 5 -Total 6 -Message \"Registrando protocolo personalizado...\"",
    "    Write-Host \"   Esto permitira que la aplicacion web abra el TPV.\"",
    "    Write-Host \"   Protocolo: $PROTOCOL_URL\"",
    "    Write-Host \"\"",
    "",
    "    try {",
    "        $protocolKey = \"Registry::HKEY_CURRENT_USER\\Software\\Classes\\$PROTOCOL\"",
    "",
    "        if (-not (Test-Path $protocolKey)) {",
    "            New-Item -Path $protocolKey -Force | Out-Null",
    "        }",
    "",
    "        Set-ItemProperty -Path $protocolKey -Name \"(Default)\" -Value \"URL:$APP_NAME Protocol\"",
    "        Set-ItemProperty -Path $protocolKey -Name \"URL Protocol\" -Value \"\"",
    "",
    "        $commandKey = \"$protocolKey\\shell\\open\\command\"",
    "        if (-not (Test-Path $commandKey)) {",
    "            New-Item -Path $commandKey -Force | Out-Null",
    "        }",
    "",
    "        $cmdPath = $INSTALL_DIR",
    "        $appPath = Join-Path $INSTALL_DIR \"electron\" \"tpv-main.js\"",
    "        $commandValue = \"cmd.exe /c \"\"cd /d \"\"\" + $cmdPath + \"\"\" \"\"&\"\" node \"\"\"\"\" + $appPath + \"\"\"\"\" \"\"%1\"\"\"",
    "        Set-ItemProperty -Path $commandKey -Name \"(Default)\" -Value $commandValue",
    "",
    "        Write-Success \"Protocolo $PROTOCOL_URL registrado\"",
    "        return $true",
    "    } catch {",
    "        Record-Error \"Error al registrar el protocolo: $($_.Exception.Message)\"",
    "        Write-Host \"   El protocolo no se registro, pero la aplicacion funcionara.\" -ForegroundColor Yellow",
    "        return $true",
    "    }",
    "}",
    "",
    "function Create-Shortcuts {",
    "    Write-Step -Num 6 -Total 6 -Message \"Creando accesos directos...\"",
    "    Write-Host \"   Se crearan accesos directos en el escritorio y menu inicio.\"",
    "    Write-Host \"\"",
    "",
    "    try {",
    "        $desktopPath = [Environment]::GetFolderPath(\"Desktop\")",
    "        $startMenuPath = Join-Path ([Environment]::GetFolderPath(\"StartMenu\")) \"Programs\"",
    "",
    "        $WshShell = New-Object -ComObject WScript.Shell",
    "",
    "        $shortcut = $WshShell.CreateShortcut(\"$desktopPath\\$APP_NAME.lnk\")",
    "        $shortcut.TargetPath = \"cmd.exe\"",
    "        $shortcut.Arguments = '/c pushd \"%USERPROFILE%\\.clubviveverde-tpv\" ' + '&' + ' node electron\\tpv-main.js'",
    "        $shortcut.WorkingDirectory = \"$env:USERPROFILE\\.clubviveverde-tpv\"",
    "        $shortcut.Description = \"Sistema de Punto de Venta para Club ViveVerde\"",
    "        $shortcut.Save()",
    "        Write-Success \"Acceso directo creado en el escritorio\"",
    "",
    "        if (-not (Test-Path $startMenuPath)) {",
    "            New-Item -ItemType Directory -Path $startMenuPath -Force | Out-Null",
    "        }",
    "        $startMenuShortcut = $WshShell.CreateShortcut(\"$startMenuPath\\$APP_NAME.lnk\")",
    "        $startMenuShortcut.TargetPath = \"cmd.exe\"",
    "        $startMenuShortcut.Arguments = '/c pushd \"%USERPROFILE%\\.clubviveverde-tpv\" ' + '&' + ' node electron\\tpv-main.js'",
    "        $startMenuShortcut.WorkingDirectory = \"$env:USERPROFILE\\.clubviveverde-tpv\"",
    "        $startMenuShortcut.Description = \"Sistema de Punto de Venta para Club ViveVerde\"",
    "        $startMenuShortcut.Save()",
    "        Write-Success \"Acceso directo creado en el menu de inicio\"",
    "",
    "        return $true",
    "    } catch {",
    "        Record-Error \"Error al crear accesos directos: $($_.Exception.Message)\"",
    "        Write-Host \"   Los accesos directos no se crearon, pero la aplicacion funcionara.\" -ForegroundColor Yellow",
    "        return $true",
    "    }",
    "}",
    "",
    "function Start-Installation {",
    "    Write-Header \"$APP_NAME - Instalador\"",
    "    Write-Host \"\"",
    "    Write-Host \"Este script instalara la aplicacion TPV en tu computadora.\" -ForegroundColor White",
    "    Write-Host \"Se necesita conexion a internet y Node.js instalado.\" -ForegroundColor White",
    "    Write-Host \"\"",
    "    Write-Host \"IMPORTANTE: Si este script se cierra automaticamente,\" -ForegroundColor Yellow",
    "    Write-Host \"ejecutalo desde PowerShell para ver los mensajes de error.\" -ForegroundColor Yellow",
    "    Write-Host \"\"",
    "",
    "    $confirm = Read-Host \"Deseas continuar con la instalacion? (S/N)\"",
    "    if ($confirm -ne \"S\") {",
    "        Write-Host \"\"",
    "        Write-Host \"Instalacion cancelada por el usuario.\" -ForegroundColor Yellow",
    "        Write-Host \"Presiona Enter para salir...\"",
    "        Read-Host",
    "        exit 0",
    "    }",
    "",
    "    Write-Host \"\"",
    "    Write-Host \"Iniciando instalacion...\" -ForegroundColor Green",
    "    Write-Host \"\"",
    "",
    "    $allSuccess = $true",
    "",
    "    $result = Test-Prerequisites",
    "    if (-not $result) { $allSuccess = $false }",
    "",
    "    if ($allSuccess) {",
    "        $result = Install-Application",
    "        if (-not $result) { $allSuccess = $false }",
    "    }",
    "",
    "    if ($allSuccess) {",
    "        $result = Install-Dependencies",
    "        if (-not $result) { $allSuccess = $false }",
    "    }",
    "",
    "    if ($allSuccess) {",
    "        $result = Register-Protocol",
    "    }",
    "",
    "    if ($allSuccess) {",
    "        $result = Create-Shortcuts",
    "    }",
    "",
    "    return $allSuccess",
    "}",
    "",
    "try {",
    "    $success = Start-Installation",
    "    ",
    "    Write-Host \"\"",
    "    if ($success -and -not $scriptErrorOccurred) {",
    "        Write-Host \"========================================\" -ForegroundColor Green",
    "        Write-Host \" Instalacion COMPLETADA exitosamente!\" -ForegroundColor Green",
    "        Write-Host \"========================================\" -ForegroundColor Green",
    "        Write-Host \"\"",
    "        Write-Host \"Puedes iniciar la aplicacion de las siguientes formas:\" -ForegroundColor Cyan",
    "        Write-Host \"  1. Haz doble clic en 'Club ViveVerde TPV' en el escritorio\" -ForegroundColor White",
    "        Write-Host \"  2. Busca 'Club ViveVerde TPV' en el menu de inicio\" -ForegroundColor White",
    "        Write-Host \"  3. Haz clic en el boton del TPV en la aplicacion web\" -ForegroundColor White",
    "        Write-Host \"\"",
    "        Write-Host \"El protocolo $PROTOCOL_URL esta registrado.\" -ForegroundColor Cyan",
    "        Write-Host \"Cuando inicies sesion como cajero en la web,\" -ForegroundColor Cyan",
    "        Write-Host \"la aplicacion de escritorio se abrira automaticamente.\" -ForegroundColor Cyan",
    "    } else {",
    "        Write-Host \"\"",
    "        Write-Host \"========================================\" -ForegroundColor Red",
    "        Write-Host \" La instalacion encontro PROBLEMAS\" -ForegroundColor Red",
    "        Write-Host \"========================================\" -ForegroundColor Red",
    "        Write-Host \"\"",
    "        Write-Host \"Hubo errores durante la instalacion.\" -ForegroundColor Yellow",
    "        Write-Host \"Revisa los mensajes de error arriba para saber que salio mal.\" -ForegroundColor Yellow",
    "        Write-Host \"\"",
    "        Write-Host \"Pasos para solucionarlo:\" -ForegroundColor Cyan",
    "        Write-Host \"  1. Lee los mensajes de error arriba\" -ForegroundColor White",
    "        Write-Host \"  2. Soluciona el problema mencionado\" -ForegroundColor White",
    "        Write-Host \"  3. Ejecuta este script de nuevo\" -ForegroundColor White",
    "        Write-Host \"\"",
    "        Write-Host \"Si necesitas ayuda, contacta al soporte tecnico.\" -ForegroundColor Cyan",
    "    }",
    "",
    "} catch {",
    "    Write-Host \"\"",
    "    Write-Host \"========================================\" -ForegroundColor Red",
    "    Write-Host \" Error INESPERADO durante la instalacion\" -ForegroundColor Red",
    "    Write-Host \"========================================\" -ForegroundColor Red",
    "    Write-Host \"\"",
    "    Write-Host \"Detalles del error:\" -ForegroundColor Red",
    "    Write-Host \"$($_.Exception.Message)\" -ForegroundColor White",
    "    Write-Host \"\"",
    "    Write-Host \"Por favor, intenta de nuevo o contacta al soporte tecnico.\" -ForegroundColor Yellow",
    "}",
    "",
    "Write-Host \"\"",
    "Write-Host \"========================================\" -ForegroundColor Gray",
    "Write-Host \" Presiona Enter para salir...\" -ForegroundColor Gray",
    "Write-Host \"========================================\" -ForegroundColor Gray",
    "Read-Host",
  ];

  return lines.join("\n");
}