/**
 * API endpoint para servir el script de instalación de Windows TPV
 */

import { NextApiRequest, NextApiResponse } from "next";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  // Solo permitir método GET
  if (req.method !== "GET") {
    return res.status(405).json({ error: "Metodo no permitido" });
  }

  // Verificar que el usuario esta autenticado y tiene rol de cajero
  try {
    const profileResp = await fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000"}/api/user/profile`, {
      headers: {
        Cookie: req.headers.cookie || "",
      },
    });

    if (!profileResp.ok) {
      return res.status(401).json({ error: "No autenticado" });
    }

    const profile = await profileResp.json();
    if (profile.user?.role !== "cajero") {
      return res.status(403).json({ error: "Acceso solo para cajeros" });
    }
  } catch {
    return res.status(401).json({ error: "No autenticado" });
  }

  // Generar el script de instalacion de PowerShell
  const installScript = generateInstallScript();

  // Configurar headers para descarga
  res.setHeader("Content-Type", "text/plain; charset=utf-8");
  res.setHeader("Content-Disposition", "attachment; filename=install-tpv-windows.ps1");

  return res.status(200).send(installScript);
}

function generateInstallScript(): string {
  const lines: string[] = [
    "# Club ViveVerde TPV - Instalador Automatico para Windows",
    "# Ejecutar como Administrador (clic derecho > Ejecutar como administrador)",
    "# Version: 1.0.0",
    "",
    "$ErrorActionPreference = \"Stop\"",
    "",
    "# Configuracion",
    "$APP_NAME = \"Club ViveVerde TPV\"",
    "$REPO_URL = \"https://github.com/idalonso123/CLUB.git\"",
    "$PROTOCOL = \"clubviveverde\"",
    "",
    "function Write-Header {",
    "    param([string]$Message)",
    "    Write-Host \"\"",
    "    Write-Host \"========================================\" -ForegroundColor Cyan",
    "    Write-Host \" $Message\" -ForegroundColor Cyan",
    "    Write-Host \"========================================\" -ForegroundColor Cyan",
    "}",
    "",
    "function Write-Step {",
    "    param([int]$Num, [int]$Total, [string]$Message)",
    "    Write-Host \"[$Num/$Total] $Message\" -ForegroundColor Yellow",
    "}",
    "",
    "function Test-Prerequisites {",
    "    Write-Step -Num 1 -Total 6 -Message \"Verificando prerequisites...\"",
    "",
    "    $nodePath = Get-Command node -ErrorAction SilentlyContinue",
    "    $gitPath = Get-Command git -ErrorAction SilentlyContinue",
    "",
    "    if (-not $nodePath) {",
    "        Write-Host \"  ERROR: Node.js no encontrado\" -ForegroundColor Red",
    "        Write-Host \"  Por favor, instala Node.js desde https://nodejs.org\" -ForegroundColor Yellow",
    "        Write-Host \"  Despues ejecuta este script de nuevo.\" -ForegroundColor Yellow",
    "        exit 1",
    "    }",
    "",
    "    if (-not $gitPath) {",
    "        Write-Host \"  ERROR: Git no encontrado\" -ForegroundColor Red",
    "        Write-Host \"  Por favor, instala Git desde https://git-scm.com\" -ForegroundColor Yellow",
    "        Write-Host \"  Despues ejecuta este script de nuevo.\" -ForegroundColor Yellow",
    "        exit 1",
    "    }",
    "",
    "    Write-Host \"  Node.js encontrado: $($nodePath.Source)\" -ForegroundColor Green",
    "    Write-Host \"  Git encontrado: $($gitPath.Source)\" -ForegroundColor Green",
    "}",
    "",
    "function Install-Application {",
    "    Write-Step -Num 2 -Total 6 -Message \"Preparando directorio de instalacion...\"",
    "",
    "    $installDir = Join-Path $env:USERPROFILE \".clubviveverde-tpv\"",
    "",
    "    # Verificar si ya existe",
    "    if (Test-Path $installDir) {",
    "        Write-Host \"  Directorio existente encontrado\" -ForegroundColor Yellow",
    "        $response = Read-Host \"  Deseas actualizar la aplicacion? (S/N)\"",
    "        if ($response -ne \"S\") {",
    "            Write-Host \"  Instalacion cancelada\" -ForegroundColor Yellow",
    "            exit 0",
    "        }",
    "        # Actualizar en vez de reinstalar",
    "        Set-Location $installDir",
    "        git pull origin main --quiet 2>$null",
    "        if ($LASTEXITCODE -ne 0) {",
    "            Write-Host \"  Intentando actualizar desde master...\" -ForegroundColor Yellow",
    "            git pull origin master --quiet 2>$null",
    "        }",
    "    } else {",
    "        Write-Host \"  Creando directorio...\" -ForegroundColor Yellow",
    "        New-Item -ItemType Directory -Path $installDir -Force | Out-Null",
    "        Set-Location $installDir",
    "",
    "        Write-Step -Num 3 -Total 6 -Message \"Clonando repositorio...\"",
    "        Write-Host \"  Esto puede tardar unos minutos...\" -ForegroundColor Gray",
    "",
    "        git clone $REPO_URL . --quiet 2>$null",
    "        if ($LASTEXITCODE -ne 0) {",
    "            git clone $REPO_URL . 2>&1 | Out-Null",
    "        }",
    "",
    "        if (-not (Test-Path \"package.json\")) {",
    "            Write-Host \"  ERROR: No se pudo clonar el repositorio\" -ForegroundColor Red",
    "            Write-Host \"  Verifica tu conexion a internet e intenta de nuevo\" -ForegroundColor Yellow",
    "            exit 1",
    "        }",
    "    }",
    "",
    "    Write-Host \"  Proyecto preparado exitosamente\" -ForegroundColor Green",
    "}",
    "",
    "function Install-Dependencies {",
    "    Write-Step -Num 4 -Total 6 -Message \"Instalando dependencias...\"",
    "    Write-Host \"  Esto puede tardar varios minutos...\" -ForegroundColor Gray",
    "",
    "    npm install 2>&1 | Out-Null",
    "",
    "    if ($LASTEXITCODE -ne 0) {",
    "        Write-Host \"  Advertencia: npm install tuvo problemas, intentando de nuevo...\" -ForegroundColor Yellow",
    "        npm install 2>&1 | Out-Null",
    "    }",
    "",
    "    if ($LASTEXITCODE -eq 0) {",
    "        Write-Host \"  Dependencias instaladas\" -ForegroundColor Green",
    "    } else {",
    "        Write-Host \"  Advertencia: Algunas dependencias pudieron no instalarse\" -ForegroundColor Yellow",
    "    }",
    "}",
    "",
    "function Register-Protocol {",
    "    Write-Step -Num 5 -Total 6 -Message \"Registrando protocolo $PROTOCOL://...\"",
    "",
    "    $protocolKey = \"Registry::HKEY_CURRENT_USER\\\\Software\\\\Classes\\\\$PROTOCOL\"",
    "",
    "    # Crear clave principal del protocolo",
    "    if (-not (Test-Path $protocolKey)) {",
    "        New-Item -Path $protocolKey -Force | Out-Null",
    "    }",
    "",
    "    Set-ItemProperty -Path $protocolKey -Name \"(Default)\" -Value \"URL:$APP_NAME Protocol\"",
    "    Set-ItemProperty -Path $protocolKey -Name \"URL Protocol\" -Value \"\"",
    "",
    "    # Crear clave del comando",
    "    $commandKey = \"$protocolKey\\\\shell\\\\open\\\\command\"",
    "    if (-not (Test-Path $commandKey)) {",
    "        New-Item -Path $commandKey -Force | Out-Null",
    "    }",
    "",
    "    # Configurar comando para ejecutar con Node",
    "    $homePath = $env:USERPROFILE",
    "    $appPath = Join-Path (Get-Location) \"electron\" \"tpv-main.js\"",
    "    $cmdPath = \"$homePath\\.clubviveverde-tpv\"",
    "    $commandValue = \"cmd /c pushd \"\"$cmdPath\"\" && node \"\"$appPath\"\"\"%1\"\"",
    "    Set-ItemProperty -Path $commandKey -Name \"(Default)\" -Value $commandValue",
    "",
    "    Write-Host \"  Protocolo $PROTOCOL:// registrado exitosamente\" -ForegroundColor Green",
    "}",
    "",
    "function Create-Shortcuts {",
    "    Write-Step -Num 6 -Total 6 -Message \"Creando accesos directos...\"",
    "",
    "    $desktopPath = [Environment]::GetFolderPath(\"Desktop\")",
    "    $startMenuPath = Join-Path ([Environment]::GetFolderPath(\"StartMenu\")) \"Programs\"",
    "",
    "    # Acceso directo principal",
    "    $WshShell = New-Object -ComObject WScript.Shell",
    "",
    "    # Acceso directo en escritorio",
    "    $shortcut = $WshShell.CreateShortcut(\"$desktopPath\\\\$APP_NAME.lnk\")",
    "    $shortcut.TargetPath = \"cmd.exe\"",
    "    $shortcut.Arguments = \"/c pushd \\\"%USERPROFILE%\\.clubviveverde-tpv\\\" && node electron\\\\tpv-main.js\"",
    "    $shortcut.WorkingDirectory = \"$env:USERPROFILE\\.clubviveverde-tpv\"",
    "    $shortcut.Description = \"Sistema de Punto de Venta para Club ViveVerde\"",
    "    $shortcut.Save()",
    "",
    "    # Acceso directo en menu inicio",
    "    $startMenuShortcut = $WshShell.CreateShortcut(\"$startMenuPath\\\\$APP_NAME.lnk\")",
    "    $startMenuShortcut.TargetPath = \"cmd.exe\"",
    "    $startMenuShortcut.Arguments = \"/c pushd \\\"%USERPROFILE%\\.clubviveverde-tpv\\\" && node electron\\\\tpv-main.js\"",
    "    $startMenuShortcut.WorkingDirectory = \"$env:USERPROFILE\\.clubviveverde-tpv\"",
    "    $startMenuShortcut.Description = \"Sistema de Punto de Venta para Club ViveVerde\"",
    "    $startMenuShortcut.Save()",
    "",
    "    Write-Host \"  Acceso directo creado en el escritorio\" -ForegroundColor Green",
    "    Write-Host \"  Acceso directo creado en el menu de inicio\" -ForegroundColor Green",
    "}",
    "",
    "function Show-Completion {",
    "    Write-Host \"\"",
    "    Write-Host \"========================================\" -ForegroundColor Green",
    "    Write-Host \" Instalacion completada!\" -ForegroundColor Green",
    "    Write-Host \"========================================\" -ForegroundColor Green",
    "    Write-Host \"\"",
    "    Write-Host \"Puedes iniciar la aplicacion de las siguientes formas:\" -ForegroundColor Cyan",
    "    Write-Host \"  1. Haz doble clic en 'Club ViveVerde TPV' en el escritorio\" -ForegroundColor White",
    "    Write-Host \"  2. Busca 'Club ViveVerde TPV' en el menu de inicio\" -ForegroundColor White",
    "    Write-Host \"  3. Haz clic en el boton del TPV en la aplicacion web\" -ForegroundColor White",
    "    Write-Host \"\"",
    "    Write-Host \"El protocolo $PROTOCOL:// esta registrado.\" -ForegroundColor Cyan",
    "    Write-Host \"Cuando inicies sesion como cajero en la web,\" -ForegroundColor Cyan",
    "    Write-Host \"la aplicacion de escritorio se abrira automaticamente.\" -ForegroundColor Cyan",
    "    Write-Host \"\"",
    "",
    "    # Esperar confirmacion del usuario",
    "    Write-Host \"Presiona Enter para salir...\" -ForegroundColor Gray",
    "    $null = Read-Host",
    "}",
    "",
    "# Ejecutar instalacion",
    "try {",
    "    Write-Header \"$APP_NAME - Instalador\"",
    "",
    "    Write-Host \"Este script instalara la aplicacion TPV en tu computadora.\" -ForegroundColor White",
    "    Write-Host \"Se necesita conexion a internet y Node.js instalado.\" -ForegroundColor White",
    "    Write-Host \"\"",
    "",
    "    $confirm = Read-Host \"Deseas continuar? (S/N)\"",
    "    if ($confirm -ne \"S\") {",
    "        Write-Host \"Instalacion cancelada\" -ForegroundColor Yellow",
    "        exit 0",
    "    }",
    "",
    "    Test-Prerequisites",
    "    Install-Application",
    "    Install-Dependencies",
    "    Register-Protocol",
    "    Create-Shortcuts",
    "    Show-Completion",
    "",
    "} catch {",
    "    Write-Host \"\"",
    "    Write-Host \"========================================\" -ForegroundColor Red",
    "    Write-Host \" Error durante la instalacion\" -ForegroundColor Red",
    "    Write-Host \"========================================\" -ForegroundColor Red",
    "    Write-Host \"\"",
    "    Write-Host \"Detalles del error: $_\" -ForegroundColor Red",
    "    Write-Host \"\"",
    "    Write-Host \"Por favor, intenta de nuevo o contacta al soporte tecnico.\" -ForegroundColor Yellow",
    "    Write-Host \"\"",
    "    Write-Host \"Presiona Enter para salir...\" -ForegroundColor Gray",
    "    $null = Read-Host",
    "    exit 1",
    "}",
  ];

  return lines.join("\n");
}